### ISSUE TITLE
Vote of Thanks 🚀

### ISSUE THREAD

**Issue by aswinmohanme** [testdouble/ecto_resource#4]
Thanks for making such an awesome library. I had always been put off by the amount of boilerplate that I had to work into Phoenix contexts for all the simple crud operations. This library cleaned up my entire context in a jiffy. Thanks so much for making such a nice and awesome library. It's not every day you find something that does what you want to do the way it's supposed to be done and nothing more.

Thanks so much for making this and more for making it available to the world. Have a great day (every day) and a great life. Cheers :D

**Comment by daytonn** [comment]
@aswinmohanme Thanks for the kind words. I'm glad you find it helpful.
