### ISSUE TITLE
Multiple resources (schemas) per context

### ISSUE THREAD

**Issue by jpaulomotta** [testdouble/ecto_resource#9]
Hello,

First of all, you did a great job on this library. Thanks so much for sharing it.

 I have a question related to using multiple schemas in a single context. Is it possible? The documentation states that it's doable, but there isn't any example on how to accomplish this.

To give an example of what I'm trying to accomplish:

Let's say we have an Account context backed by two schemas, User and Profile.

Can both be exposed as resources using this library, on the Account context?

So we'd get:

```Elixir
Account.all_users
Account.create_user
#...
Account.all_profiles
Account.create_profile
#...
```

If this isn't doable or out of the scope of this library, it's totally ok. I'm just starting to get my head around Elixir and it's conventions, and maybe I'm thinking about this problem in the wrong way.

Thanks again for the great work!  This lib is really usefull to reduce boilerplate.

**Comment by daytonn** [comment]
To do this you simply add another `resource` call, passing it the schema for which you wish to generate functions.

```elixir
defmodule MyApp.Account do
  use EctoResource
  alias MyApp.Repo
  alias MyApp.Profile
  alias MyApp.User

  using_repo(Repo) do
    resource(Profile)
    resource(User)
  end
end
```

**Comment by jpaulomotta** [comment]
Wonderful!

Thanks for the quick response.
